### ISSUE TITLE
I cant add a rainbow role

### ISSUE THREAD

**Issue by Lenni4u** [tenDevoleper/RainbowTen#2]
if i use the command addrole i get this error:
/home/pi/Desktop/TEN-RainbowBot-master/bot.js:29
        if(msg.content.startsWith(`${config.prefix}addrole`)) {
                                     ^

ReferenceError: config is not defined
    at Bot.processMessage (/home/pi/Desktop/TEN-RainbowBot-master/bot.js:29:38)
    at Client.<anonymous> (/home/pi/Desktop/TEN-RainbowBot-master/bot.js:15:57)
    at Client.emit (node:events:365:28)
    at MessageCreateHandler.handle (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:365:28)
    at Receiver.receiverOnMessage (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/ws/lib/websocket.js:789:20)

i woud realy like if you can help me with this

**Comment by Tentennnn** [comment]
fix **${config.prefix}addrole** to **${Config.prefix}addrole**

**Comment by Tentennnn** [comment]
fix **${config.prefix}addrole** to **${Config.prefix}addrole**

**Comment by Lenni4u** [comment]
now it sayes this:

ReferenceError: config is not defined
    at Bot.processMessage (/home/pi/Desktop/TEN-RainbowBot-master/bot.js:29:38)
    at Client.<anonymous> (/home/pi/Desktop/TEN-RainbowBot-master/bot.js:15:57)
    at Client.emit (node:events:365:28)
    at MessageCreateHandler.handle (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:365:28)
    at Receiver.receiverOnMessage (/home/pi/Desktop/TEN-RainbowBot-master/node_modules/ws/lib/websocket.js:789:20)

**Comment by Lenni4u** [comment]
now it sayes this:/home/pi/Desktop/TEN-RainbowBot-master/bot.js:1
gvar discord = require('discord.js');
     ^^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
