### ISSUE TITLE
im back for a other question 

### ISSUE THREAD

**Issue by Lenni4u** [tenDevoleper/RainbowTen#4]
/home/pi/Desktop/TEN-RainbowBot-master/bot.js:40
            var liveGuild = this.discordClient.guilds.cache.get(server);
                                                                                     ^

TypeError: Cannot read property 'get' of undefined
    at Bot.randomizeRoleColors (/home/pi/Desktop/TEN-RainbowBot-master/bot.js:40:61)
    at Timeout._onTimeout (/home/pi/Desktop/TEN-RainbowBot-master/bot.js:24:18)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

sorry i doun't know wat this means i hope you can help me thanks

**Comment by Lenni4u** [comment]
the arrow is under the g out of get

**Comment by Tentennnn** [comment]
> the arrow is under the g out of get

please new update bro

**Comment by Lenni4u** [comment]
i update it an like 5 min ago

**Comment by Lenni4u** [comment]
mabe 10 mins

**Comment by Lenni4u** [comment]
h
