### ISSUE TITLE
I get this error in newest version

### ISSUE THREAD

**Issue by Lenni4u** [tenDevoleper/RainbowTen#5]
i checked again and i have defeitly the newest version and i get this error:
/home/pi/Desktop/TEN-RainbowBot-master/bot.js:40
            var liveGuild = this.discordClient.guilds.cache.get(server);
                                                            ^

TypeError: Cannot read property 'get' of undefined
    at Bot.randomizeRoleColors (/home/pi/Desktop/TEN-RainbowBot-master/bot.js:40:61)
    at Timeout._onTimeout (/home/pi/Desktop/TEN-RainbowBot-master/bot.js:24:18)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

i hope you can help me 
thanks

**Comment by HRahul007** [comment]
> i checked afain and i have defeitly the newest version and i get this error:
> /home/pi/Desktop/TEN-RainbowBot-master/bot.js:40
> var liveGuild = this.discordClient.guilds.cache.get(server);
> ^
> 
> TypeError: Cannot read property 'get' of undefined
> at Bot.randomizeRoleColors (/home/pi/Desktop/TEN-RainbowBot-master/bot.js:40:61)
> at Timeout._onTimeout (/home/pi/Desktop/TEN-RainbowBot-master/bot.js:24:18)
> at listOnTimeout (node:internal/timers:557:17)
> at processTimers (node:internal/timers:500:7)
> 
> i hope you can help me
> thanks

i ALso have same problem
